dist: bionic

git:
  depth: 5

matrix:
  include:
    - env:
        - task=shellcheck
      language: node_js
      node_js:
        - "12"
      cache:
        directories:
          - .npx
      script:
        - npx --cache .npx dockerfile_lint
    - env:
        - task=Docker build
      language: minimal
      services:
        - docker
      script:
        - docker build -t tor-socks-proxy:$TRAVIS_COMMIT .
